version: "3.7"

services:
  app:
    build: .
    depends_on:
      - db
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - ./dbscripts/1.sql:/docker-entrypoint-initdb.d/1.sql
      - ./dbscripts/2.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER:  "energy"
      POSTGRES_PASSWORD: "samplepassword"
